### PR TITLE
enable proxysql compatibility by updating mysql-otp

### PR DESCRIPTION
**Pull request by phanimahesh**
Proxysql has a bug, where it changes the reported value of `SERVER_STATUS_AUTOCOMMIT` just after authentication.

Mysql-otp used to check that the status bits did not change, (all except `SERVER_SESSION_STATE_CHANGED`) using an assertion (See https://github.com/mysql-otp/mysql-otp/blob/1.3.2/src/mysql_protocol.erl#L75-L76), which crashed connections with proxysql.

I intended to make a quick dirty fix by ignoring that bit change, but looks like the exact same fix was already proposed and merged upstream in commit https://github.com/mysql-otp/mysql-otp/commit/f43adad8e0a50c8f8120c407ec820d35add2f219

### CODE REVIEW

**Comment by Gilbert-Wong** [comment]
I suppose it is better to specify the dep tag rather dep branch in project

**Comment by phanimahesh** [comment]
We have to fork and tag it, that commit is untagged.

**Comment by phanimahesh** [comment]
There's a dep hook that forces the commit even in erlang.mk, so we can reproduce the build later. It is in a sense even better than the tag, tags may be force updated.

It doesn't look that neat in erlang.mk though.

What do you prefer? We make a fork, tag it and use it, or we just use the commit locking as I set it up?

**Comment by Gilbert-Wong** [comment]
Hi, @phanimahesh, your code base is too old and I cannot rebase your code on your own repo. So I open a new pull request here https://github.com/emqx/emqx-auth-mysql/pull/150. Anyway, really appreciate your work and thanks for your contribution. You are a member of the emqx organization, so I suggest you directly create a new branch in emqx repo rather fork it to your own repo. :)

**Comment by phanimahesh** [comment]
👍

**Pull request closed without merging**
